// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team4041.robot.commands;

import edu.wpi.first.wpilibj.command.Subsystem;

public class  DriveStraighter extends PIDCommandBase{

	private double distance; 
	private double maxspeed;
	
	public final static double kp = 0.078;
	public final static double ki = 0;
	public final static double kd = 0.6;
	public final static double max = 0.8;
	public final static double period = 0.01;
	
	public DriveStraighter(double distance, double p, double i, double d, double max ) {	
		super("a_drive_move_dist_straight", p, i, d, period);
		this.distance = distance;
		this.maxspeed = max;
		getPIDController().setContinuous(false);
        getPIDController().setAbsoluteTolerance(0.2);
        
        requires((Subsystem) driveTrain);
	}
    
    public DriveStraighter(double distance, double maxspeed) {
    	this(distance, kp, ki, kd, maxspeed);
    }
    public DriveStraighter(double distance) {
    	this(distance, max);
    }
    
    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;
//    	System.out.println("PIDGET: "+RobotMap.driveLeftEncoder.pidGet());
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        return driveTrain.getRightEncoder().pidGet();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
    }

    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
    	output = constrain(-maxspeed, output, maxspeed);
    	if (Math.abs(output) < .4 && output != 0) {
    		output = (output/Math.abs(output))*.4;
    	}
    	if ((timeSinceInitialized()+.4)<1) {
    		 output = output * (timeSinceInitialized()+.4);
    	}
    		
    	driveTrain.driveStraighter(-output);
//    	Robot.drive.HDrive(-output, 0, 0);
//    	System.out.println("PIDOUT: "+output);
    }
    
    private double constrain(double min, double value, double max){
    	if(value > max){
    		return max;
    	}
    	else if(value < min){
    		return min;
    	}
    	else{
    		return value;
    	}
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	driveTrain.getRightEncoder().reset();
    	driveTrain.resetGyro();
    	getPIDController().setSetpoint(distance);
    	getPIDController().enable();
//    	System.out.println("INIT "+U.className(this));
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
//    	System.out.println("EXEC a_drive_move_dist");
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
//    	System.out.println("----ERROR: "+getPIDController().getError()+" R:"+RobotMap.driveLeftEncoder.getRate());
//    	return getPIDController().getError() <= THRESH;
    	return Math.abs(getPIDController().getError()) <= 1.5;// && RobotMap.driveLeftEncoder.getRate() < .5
    	//return getPIDController().onTarget();
    }

    // Called once after isFinished returns true
    protected void end() {
//    	System.out.println("END");
    	getPIDController().disable();
    	driveTrain.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
//    	System.out.println("INT");
    	end();
    }
}
